server:
  port: 9999

spring:
  application:
    name: "Math Bilim"
    version: 1.0.2

  datasource:
    url: jdbc:postgresql://localhost:5432/mathbilim
    username: mvoin21
    password: qwerty
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  output:
    ansi:
      enabled: always

  security:
    user:
      name: email
      password: password

  freemarker:
    expose-session-attributes: true
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7